name: Format Check

on:
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Fetch base branch
      run: git fetch origin ${{ github.base_ref }} --depth=1

    - run: npm ci

    - name: Install Biome
      run: npm install @biomejs/biome

    - name: Get changed files
      id: changed-files
      run: |
        echo "files=$(git diff --name-only --diff-filter=ACMRT origin/${{ github.base_ref }} ${{ github.event.pull_request.head.sha }} | grep '\.js\|\.ts\|\.jsx\|\.tsx$' | xargs)" >> $GITHUB_OUTPUT

    - name: Check Formatting
      run: |
        if [ "${{ steps.changed-files.outputs.files }}" != "" ]; then
          echo "Files to be checked:"
          echo "${{ steps.changed-files.outputs.files }}"
          bash ./docker/check-format.sh ${{ steps.changed-files.outputs.files }}
        else
          echo "No relevant files changed."
        fi