name: Format Check

on:
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
    - uses: actions/checkout@v4
    - run: npm ci
    - name: Install Biome
      run: npm install @biomejs/biome
    - name: Check Formatting
      run: bash ./check-format.sh